# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian
  amd64: ghcr.io/home-assistant/amd64-base-debian
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Example add-on"
  org.opencontainers.image.description: "Water meter OCR with Azure vision and tapo camera"
  org.opencontainers.image.source: "https://github.com/tle06/eaubbies"
  org.opencontainers.image.licenses: "MIT"
