---
name: Eaubbies
version: "0.0.30"
slug: eaubbies
description: Water meter OCR with Azure vision and tapo camera
url: "https://github.com/tle06/eaubbies"
arch:
  - amd64
  - aarch64
init: false
map:
  - share:rw
schema:
  message: "str?"
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: "tlnk/{arch}-addon-eaubbies"
ingress: true
panel_icon: mdi:water
