# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Eaubbies
version: "1.2.0"
slug: eaubbies
description: Water meter OCR with Azure vision and tapo camera
url: "https://github.com/tle06/eaubbies"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "tlnk/{arch}-addon-eaubbies"
