---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target eaubbies \
            --docker-hub tlnk
